logging:
  level:
    root: INFO
    com.example.send_hii: DEBUG

spring:
  application:
    name: whatsapp-integration

whatsapp:
  mode: subscribe
  verification_token: kartikaryan
  api:
    url: https://graph.facebook.com/v20.0/317367008136487/messages
    token: EAAXdPN7JNQgBO747e7hhPBUyia9JxwpSa5HsWWYCcvOVAftraPJswho2yPWfXWzjJi95ZCcdoVZCvZAjQOHkqX1HrpoZBxtcfK5k0cLNIuddXj2U4ttzyI38ZCtAEjvSrPek8Ahk82QLqPcAx5q8cqlAHerzMsA2hR8VThXb0tdU52Y6gG5OsDrZCkKZCG2g4YSoA5sVBE6YzBZAWx5rW5ZCgZBAFmhSraqC6Eo9IZD
server:
  port: 9001