spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/whatsapp?currentSchema=user
    username: postgres
    password: root
    hikari:
      data-source-properties:
        stringtype: unspecified
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        maintainTimeStats: false
        maximum-pool-size: 5
        connection-timeout: 5000
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
      dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: none
    show-sql: false
    open-in-view: false
    generate-ddl: false
whatsapp:
  mode: subscribe
  verification_token: kartikaryan
  api:
    url: https://graph.facebook.com/v20.0/317367008136487/messages
    token: EAAXdPN7JNQgBO23IZAVlGnji1W4STB7FSR1tdN8fUddvsu40s2QVoEA74VapKbaxVb6J4smSpA3PahA5R9WAmOSeSaNKLzEV5nNaYsZAVJstyAjGkuSZATH0Yq9VZCHBUOFNDPDov39oJUEFqls9ShXCtmIEgt24CE2ZBSoPdunZAnKBs2BlGXKNhWR8fPihhZBPGTSgWkiVZBwaLzlB80jUeHY8DCNgwZCTH3sOz
server:
  port: 9001